name: Rust

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  coverage:

    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1.0
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
